# Generated by Django 4.0.4 on 2022-06-05 09:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_alter_productcategory_name_and_more'),
        ('contractors', '0003_alter_contractor_category_alter_contractor_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('is_handed', models.BooleanField(default=False, verbose_name='Выставлен клиенту')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='contractors.contractorsobject', verbose_name='Объект')),
                ('product_list', models.ManyToManyField(to='products.products', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
            },
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('state', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('ordered', 'Размещена у поставщика'), ('on_store', 'Получена от поставщика'), ('delivered', 'Доставлена клиенту'), ('paid', 'Оплачена'), ('done', 'Закрыта')], default='Новая', max_length=255, verbose_name='Статус')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='contractors.contractorsobject', verbose_name='Объект')),
                ('product_list', models.ManyToManyField(to='products.products', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
