# Generated by Django 4.0.4 on 2022-05-26 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractors', '0002_alter_contractor_address_alter_contractor_category_and_more'),
        ('products', '0002_alter_productcategory_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('state', models.BooleanField(default=False, verbose_name='Статус')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.contractorsobject', verbose_name='Объект')),
                ('product_list', models.ManyToManyField(to='products.products', verbose_name='Товары')),
            ],
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.contractorsobject', verbose_name='Объект')),
                ('product_list', models.ManyToManyField(to='products.products', verbose_name='Товары')),
            ],
        ),
    ]
