# Generated by Django 4.0.4 on 2022-05-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='state',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('invoced', 'Выставлен счет клиенту'), ('ordered', 'Размещена у поставщика'), ('on_store', 'Получена от поставщика'), ('delivered', 'Доставлена клиенту'), ('paid', 'Оплачена'), ('done', 'Закрыта')], default='Новая', max_length=255, verbose_name='Статус'),
        ),
    ]
