# Generated by Django 4.0.4 on 2022-06-05 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_demand_options_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='obj',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='product_list',
        ),
        migrations.DeleteModel(
            name='Demand',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
