# Generated by Django 4.0.4 on 2022-05-27 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0002_alter_contractor_address_alter_contractor_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='category',
            field=models.ForeignKey(blank=True, default='Категория по умолчанию', null=True, on_delete=django.db.models.deletion.RESTRICT, to='contractors.contractorcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='contractorcategory',
            name='name',
            field=models.CharField(default='Категория по умолчанию', max_length=255, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='contractorsobject',
            name='contractor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='contractors.contractor', verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='contractorsobject',
            name='name',
            field=models.CharField(blank=True, default='Объект не указан', max_length=255, null=True, verbose_name='Наименование'),
        ),
    ]
