# Generated by Django 4.0.4 on 2022-05-27 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productcategory_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(default='Категория по умолчанию', max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, default='Категория по умолчанию', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.productcategory', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='products.productcategory', verbose_name='Категория товара'),
        ),
    ]
